libdsme,mce: Inherit pkgconfig
wrynose no longer exports PKG_CONFIG_PATH unless a recipe inherits
pkgconfig.
Both Makefiles call pkg-config themselves, so glib.h is no longer
found:
| protocol.c:34:10: fatal error: glib.h: No such file or directory

Signed-off-by: Darrel Griët <dgriet@gmail.com>