dbus: Remove specialized configuration for geoclue-hybris
This removes the dbus configuration originally introduced in
https://github.com/AsteroidOS/meta-asteroid/commit/458d248b2ca34daebbde8784fbba291f95d60d9e
as the original geoclue v0 plugin is not longer available on
Qt6Positioning.

Additionally this fixes a packaging issue for nativesdk-dbus:
ERROR: nativesdk-dbus-1.16.2-r0 do_package: QA Issue: nativesdk-dbus: Files/directories were installed but not shipped in any package:
  /usr/share
  /usr/share/dbus-1
  /usr/share/dbus-1/session.d
  /usr/share/dbus-1/session.d/session-local.conf
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
nativesdk-dbus: 4 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Darrel Griët <dgriet@gmail.com>